export const routePaths = {
    login: '/login',
    home: '/',
    calendar: '/calendar',
    appointmentSchedule: '/appointments/new/schedule',
    appointmentFriends: '/appointments/new/friends',
    appointmentGroups: '/appointments/new/groups',
    invite: '/invite/:inviteToken',
    friends: '/friends',
    chat: '/chat',
    chatDirect: '/chat/direct',
    chatAppointments: '/chat/appointments',
    chatUnread: '/chat/unread',
    chatAll: '/chat/all',
    chatRoomPattern: '/chat/rooms/:roomId',
    chatRoom: (roomId: string) => `/chat/rooms/${roomId}`,
    notifications: '/notifications',
    mypage: '/mypage',
} as const;
